services:
  postgres:
    image: postgres:17
    container_name: postgres_adopsi
    restart: always
    environment:
      POSTGRES_DB: adopsi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_adopsi
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jelly@gmail.com
      PGADMIN_DEFAULT_PASSWORD: jelly1245
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: