services:
  mysql:
    image: mysql:8.0
    container_name: mysql_adopsi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adopsi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_adopsi
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"

volumes:
  mysql_data: