const express = require("express")
const superadminController = require("../controllers/superadminController")

const router = express.Router()

router.get("/superadmin/dashboard", superadminController.getDashboard)
router.get("/superadmin/users", superadminController.getUsers)
router.post("/superadmin/users", superadminController.createUser)
router.put("/superadmin/users/:id", superadminController.updateUser)
router.delete("/superadmin/users/:id", superadminController.deleteUser)
router.get("/superadmin/deleted-users", superadminController.getDeletedUsers)
router.post("/superadmin/users/:id/restore", superadminController.restoreUser)
router.get("/superadmin/animals", superadminController.getAnimals)
router.post("/superadmin/animals", superadminController.createAnimal)
router.put("/superadmin/animals/:id", superadminController.updateAnimal)
router.delete("/superadmin/animals/:id", superadminController.deleteAnimal)
router.get("/superadmin/deleted-animals", superadminController.getDeletedAnimals)
router.post("/superadmin/animals/:id/restore", superadminController.restoreAnimal)
router.get("/superadmin/categories", superadminController.getCategories)
router.post("/superadmin/categories", superadminController.createCategory)
router.put("/superadmin/categories/:id", superadminController.updateCategory)
router.delete("/superadmin/categories/:id", superadminController.deleteCategory)
router.get("/superadmin/deleted-categories", superadminController.getDeletedCategories)
router.post("/superadmin/categories/:id/restore", superadminController.restoreCategory)
router.get("/superadmin/adoption-requests", superadminController.getAdoptionRequests)
router.put("/superadmin/adoption-requests/:id", superadminController.updateAdoptionRequest)
router.delete("/superadmin/adoption-requests/:id", superadminController.deleteAdoptionRequest)
router.get("/superadmin/deleted-adoption-requests", superadminController.getDeletedAdoptionRequests)
router.post("/superadmin/adoption-requests/:id/restore", superadminController.restoreAdoptionRequest)
router.get("/superadmin/questionnaire-questions", superadminController.getQuestionnaireQuestions)
router.post("/superadmin/questionnaire-questions", superadminController.createQuestionnaireQuestion)
router.put("/superadmin/questionnaire-questions/:id", superadminController.updateQuestionnaireQuestion)
router.delete("/superadmin/questionnaire-questions/:id", superadminController.deleteQuestionnaireQuestion)
router.get("/superadmin/deleted-questionnaire-questions", superadminController.getDeletedQuestionnaireQuestions)
router.post("/superadmin/questionnaire-questions/:id/restore", superadminController.restoreQuestionnaireQuestion)
router.get("/superadmin/settings", superadminController.getSettings)
router.put("/superadmin/settings", superadminController.updateSettings)
router.get("/superadmin/profile", superadminController.getProfile)
router.put("/superadmin/profile", superadminController.updateProfile)

router.get("/superadmin/reports", superadminController.getReports)
router.get("/superadmin/activity-logs", superadminController.getActivityLogs)
router.post("/superadmin/activity-logs", superadminController.createActivityLog)

router.get("/superadmin/backup/export", superadminController.exportBackup)
router.post("/superadmin/backup/import", superadminController.importBackup)

module.exports = router
